### ISSUE TITLE
Example app

### ISSUE THREAD

**Issue by markkrenek** [Dschee/Imperio#1]
This repo looks great. I'm going to try to use it for a new project. It would be great if you had a sample app that pulled together all the code snippets in your read me.

**Comment by Jeehut** [comment]
Sorry for answering so late, somehow I didn't receive the mail or I accidentally deleted it. 😞 

Thanks for asking this question. I agree that a minimal example project would be great. I'm not sure though when I will be able to implement it (a PR would be welcome of course) – until then you can refer to an non-minimal example app, which is also the first project I used this library:

I've [open sourced](https://github.com/Flinesoft/Prayer) an app about Islamic Prayers where you can see this used within the [SettingsCoordinator](https://github.com/Flinesoft/Prayer/blob/stable/Sources/Code/SettingsCoordinator.swift)/[ViewController](https://github.com/Flinesoft/Prayer/blob/stable/Sources/Code/SettingsViewController.swift) and [PrayerCoordinator](https://github.com/Flinesoft/Prayer/blob/stable/Sources/Code/PrayerCoordinator.swift)/[ViewController](https://github.com/Flinesoft/Prayer/blob/stable/Sources/Code/PrayerViewController.swift).

I hope this helps until an example project is implemented.

**Comment by Jeehut** [comment]
I've just released version 2.0.0 which contains a demo project. This is fixed now.
